"""Add review workflow models

Revision ID: 703cc5dadf8e
Revises: 
Create Date: 2025-09-01 14:50:11.938605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703cc5dadf8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_test_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('assignee_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', 'CANCELLED', name='reviewstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reviewpriority'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('workflow_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['generated_test_id'], ['generated_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_workflows_generated_test_id'), 'review_workflows', ['generated_test_id'], unique=False)
    op.create_index(op.f('ix_review_workflows_id'), 'review_workflows', ['id'], unique=False)
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_workflow_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('comment_type', sa.Enum('GENERAL', 'ISSUE', 'SUGGESTION', 'QUESTION', 'APPROVAL', name='commenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('comment_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['review_workflow_id'], ['review_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comments_id'), 'review_comments', ['id'], unique=False)
    op.create_index(op.f('ix_review_comments_review_workflow_id'), 'review_comments', ['review_workflow_id'], unique=False)
    op.create_table('review_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_workflow_id', sa.Integer(), nullable=False),
    sa.Column('time_to_first_response_minutes', sa.Integer(), nullable=True),
    sa.Column('time_to_completion_minutes', sa.Integer(), nullable=True),
    sa.Column('total_comments', sa.Integer(), nullable=True),
    sa.Column('issues_found', sa.Integer(), nullable=True),
    sa.Column('suggestions_made', sa.Integer(), nullable=True),
    sa.Column('revisions_requested', sa.Integer(), nullable=True),
    sa.Column('code_quality_score', sa.Integer(), nullable=True),
    sa.Column('test_coverage_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_workflow_id'], ['review_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_metrics_id'), 'review_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_review_metrics_review_workflow_id'), 'review_metrics', ['review_workflow_id'], unique=False)
    op.add_column('webhook_events', sa.Column('processing_metadata', sa.JSON(), nullable=True))
    op.add_column('webhook_events', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'error_message')
    op.drop_column('webhook_events', 'processing_metadata')
    op.drop_index(op.f('ix_review_metrics_review_workflow_id'), table_name='review_metrics')
    op.drop_index(op.f('ix_review_metrics_id'), table_name='review_metrics')
    op.drop_table('review_metrics')
    op.drop_index(op.f('ix_review_comments_review_workflow_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_id'), table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_index(op.f('ix_review_workflows_id'), table_name='review_workflows')
    op.drop_index(op.f('ix_review_workflows_generated_test_id'), table_name='review_workflows')
    op.drop_table('review_workflows')
    # ### end Alembic commands ###
