"""add approval workflow system

Revision ID: d223e3eba919
Revises: 703cc5dadf8e
Create Date: 2025-09-01 15:57:02.347613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd223e3eba919'
down_revision: Union[str, Sequence[str], None] = '703cc5dadf8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='approvalworkflowstatus'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('requires_all_stages', sa.Boolean(), nullable=False),
    sa.Column('auto_advance', sa.Boolean(), nullable=False),
    sa.Column('allow_parallel_approvals', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('workflow_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_table('workflow_sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reviewpriority'), nullable=False),
    sa.Column('initial_response_minutes', sa.Integer(), nullable=False),
    sa.Column('completion_minutes', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_percent', sa.Integer(), nullable=True),
    sa.Column('escalation_threshold_percent', sa.Integer(), nullable=True),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_reassign_enabled', sa.Boolean(), nullable=True),
    sa.Column('escalation_recipients', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_sla_policies_id'), 'workflow_sla_policies', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_sla_policies_priority'), 'workflow_sla_policies', ['priority'], unique=True)
    op.create_table('approval_workflow_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('required_roles', sa.JSON(), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('timeout_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stage_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_workflow_stages_id'), 'approval_workflow_stages', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflow_stages_workflow_id'), 'approval_workflow_stages', ['workflow_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('review_workflow_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reviewpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['current_stage_id'], ['approval_workflow_stages.id'], ),
    sa.ForeignKeyConstraint(['review_workflow_id'], ['review_workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_current_stage_id'), 'approval_requests', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_approval_requests_review_workflow_id'), 'approval_requests', ['review_workflow_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_workflow_id'), 'approval_requests', ['workflow_id'], unique=False)
    op.create_table('workflow_sla_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_workflow_id', sa.Integer(), nullable=False),
    sa.Column('sla_policy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ON_TRACK', 'AT_RISK', 'BREACHED', 'ESCALATED', name='slastatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('initial_response_due_at', sa.DateTime(), nullable=False),
    sa.Column('completion_due_at', sa.DateTime(), nullable=False),
    sa.Column('initial_response_breached', sa.Boolean(), nullable=True),
    sa.Column('completion_breached', sa.Boolean(), nullable=True),
    sa.Column('breach_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('warning_sent_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=True),
    sa.Column('last_escalation_type', sa.Enum('WARNING', 'ESCALATION', 'CRITICAL_ESCALATION', name='escalationtype'), nullable=True),
    sa.Column('time_to_first_response_minutes', sa.Integer(), nullable=True),
    sa.Column('time_to_completion_minutes', sa.Integer(), nullable=True),
    sa.Column('sla_compliance_score', sa.Integer(), nullable=True),
    sa.Column('tracking_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_workflow_id'], ['review_workflows.id'], ),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['workflow_sla_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_sla_tracking_id'), 'workflow_sla_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_sla_tracking_review_workflow_id'), 'workflow_sla_tracking', ['review_workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_sla_tracking_sla_policy_id'), 'workflow_sla_tracking', ['sla_policy_id'], unique=False)
    op.create_table('approval_stage_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approvals_received', sa.Integer(), nullable=False),
    sa.Column('approvals_required', sa.Integer(), nullable=False),
    sa.Column('stage_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['approval_workflow_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_stage_instances_id'), 'approval_stage_instances', ['id'], unique=False)
    op.create_index(op.f('ix_approval_stage_instances_request_id'), 'approval_stage_instances', ['request_id'], unique=False)
    op.create_index(op.f('ix_approval_stage_instances_stage_id'), 'approval_stage_instances', ['stage_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('stage_instance_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.String(length=255), nullable=False),
    sa.Column('approver_role', sa.Enum('DEVELOPER', 'REVIEWER', 'QA_LEAD', 'TECH_LEAD', 'SENIOR_DEVELOPER', 'ADMIN', name='reviewrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approval_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['stage_instance_id'], ['approval_stage_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_request_id'), 'approvals', ['request_id'], unique=False)
    op.create_index(op.f('ix_approvals_stage_instance_id'), 'approvals', ['stage_instance_id'], unique=False)
    op.add_column('webhook_events', sa.Column('processing_metadata', sa.JSON(), nullable=True))
    op.add_column('webhook_events', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'error_message')
    op.drop_column('webhook_events', 'processing_metadata')
    op.drop_index(op.f('ix_approvals_stage_instance_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_request_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_approval_stage_instances_stage_id'), table_name='approval_stage_instances')
    op.drop_index(op.f('ix_approval_stage_instances_request_id'), table_name='approval_stage_instances')
    op.drop_index(op.f('ix_approval_stage_instances_id'), table_name='approval_stage_instances')
    op.drop_table('approval_stage_instances')
    op.drop_index(op.f('ix_workflow_sla_tracking_sla_policy_id'), table_name='workflow_sla_tracking')
    op.drop_index(op.f('ix_workflow_sla_tracking_review_workflow_id'), table_name='workflow_sla_tracking')
    op.drop_index(op.f('ix_workflow_sla_tracking_id'), table_name='workflow_sla_tracking')
    op.drop_table('workflow_sla_tracking')
    op.drop_index(op.f('ix_approval_requests_workflow_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_review_workflow_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_current_stage_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_workflow_stages_workflow_id'), table_name='approval_workflow_stages')
    op.drop_index(op.f('ix_approval_workflow_stages_id'), table_name='approval_workflow_stages')
    op.drop_table('approval_workflow_stages')
    op.drop_index(op.f('ix_workflow_sla_policies_priority'), table_name='workflow_sla_policies')
    op.drop_index(op.f('ix_workflow_sla_policies_id'), table_name='workflow_sla_policies')
    op.drop_table('workflow_sla_policies')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
