openapi: 3.0.0
info:
  title: Circular References Test API
  version: 1.0.0
  description: Tests circular schema references handling
servers:
  - url: https://api.example.com/v1

paths:
  /users/{userId}:
    get:
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User with friends
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /organizations/{orgId}:
    get:
      operationId: getOrganization
      parameters:
        - name: orgId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Organization with departments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        friends:
          type: array
          items:
            $ref: '#/components/schemas/User'  # Circular reference
        organization:
          $ref: '#/components/schemas/Organization'

    Organization:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        employees:
          type: array
          items:
            $ref: '#/components/schemas/User'  # Circular reference
        departments:
          type: array
          items:
            $ref: '#/components/schemas/Department'

    Department:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        manager:
          $ref: '#/components/schemas/User'  # Circular reference
        organization:
          $ref: '#/components/schemas/Organization'  # Circular reference